
postgres: &postgres
  adapter: postgresql
  host: localhost
  username: plymlet
  password: blocio

development:
  <<: *postgres
  database: plymlet_development

test:
  <<: *postgres
  database: plymlet_test

production:
  <<: *postgres
  database: plymlet_production
